### ISSUE TITLE
unit tests are failing

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpfit#2]
Traceback below. 

```
======================================================================
FAIL: test_MA (t_print_fit.t_print_MA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpfit/gpfit/tests/t_print_fit.py", line 17, in test_MA
    'w = 8.1e+03 * (u_0)**10 * (u_1)**11 * (u_2)**12'])
AssertionError: Lists differ: ['w = 2.72 * (u_1)**2 * (u_2)*... != ['w = 2.72 * (u_0)**2 * (u_1)*...

First differing element 0:
w = 2.72 * (u_1)**2 * (u_2)**3 * (u_3)**4
w = 2.72 * (u_0)**2 * (u_1)**3 * (u_2)**4

- ['w = 2.72 * (u_1)**2 * (u_2)**3 * (u_3)**4',
-  'w = 148 * (u_1)**6 * (u_2)**7 * (u_3)**8',
-  'w = 8.1e+03 * (u_1)**10 * (u_2)**11 * (u_3)**12']
+ ['w = 2.72 * (u_0)**2 * (u_1)**3 * (u_2)**4',
+  'w = 148 * (u_0)**6 * (u_1)**7 * (u_2)**8',
+  'w = 8.1e+03 * (u_0)**10 * (u_1)**11 * (u_2)**12']

======================================================================
FAIL: test_SMA (t_print_fit.t_print_SMA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpfit/gpfit/tests/t_print_fit.py", line 32, in test_SMA
    '    + 2 * (u_0)**0.769 * (u_1)**0.846 * (u_2)**0.923'])
AssertionError: Lists differ: ['w**0.0769 = 1.08 * (u_1)**0.... != ['w**0.0769 = 1.08 * (u_0)**0....

First differing element 0:
w**0.0769 = 1.08 * (u_1)**0.154 * (u_2)**0.231 * (u_3)**0.308
w**0.0769 = 1.08 * (u_0)**0.154 * (u_1)**0.231 * (u_2)**0.308

- ['w**0.0769 = 1.08 * (u_1)**0.154 * (u_2)**0.231 * (u_3)**0.308',
-  '    + 1.47 * (u_1)**0.462 * (u_2)**0.538 * (u_3)**0.615',
-  '    + 2 * (u_1)**0.769 * (u_2)**0.846 * (u_3)**0.923']
+ ['w**0.0769 = 1.08 * (u_0)**0.154 * (u_1)**0.231 * (u_2)**0.308',
+  '    + 1.47 * (u_0)**0.462 * (u_1)**0.538 * (u_2)**0.615',
+  '    + 2 * (u_0)**0.769 * (u_1)**0.846 * (u_2)**0.923']

======================================================================
FAIL: test_ISMA (t_print_fit.t_print_ISMA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpfit/gpfit/tests/t_print_fit.py", line 47, in test_ISMA
    '    + (1.82/w**0.0667) * (u_0)**0.667 * (u_1)**0.733 * (u_2)**0.8'])
AssertionError: Lists differ: ['1 = (1.08/w**0.0769) * (u_1)... != ['1 = (1.08/w**0.0769) * (u_0)...

First differing element 0:
1 = (1.08/w**0.0769) * (u_1)**0.154 * (u_2)**0.231 * (u_3)**0.308
1 = (1.08/w**0.0769) * (u_0)**0.154 * (u_1)**0.231 * (u_2)**0.308

Diff is 803 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 47 tests in 0.136s

FAILED (failures=3)
```

**Comment by bqpd** [comment]
I don't even have that test on my computer yet.

**Comment by bqpd** [comment]
(I keep confusing gpfit issues for gpkit issues, lolz)
